### ISSUE TITLE
Handle the peppol-python just like a new library of python that contains the functionalities of peppol?

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/peppol-python#8]
Do we intend to create a website/application which we will manage?

If so,  we must discuss and design the business logic!

Otherwise, each developer-user must implement its own application(API, frontend, database) and just include the peppol-python library.

**Comment by michielbdejong** [comment]
Yes, as discussed this morning, I think it makes sense if we say https://github.com/pondersource/peppol-python is our library, and https://github.com/pondersource/peppol-python-demo is the Django-based website that uses it.
